### ISSUE TITLE
Hash the program before compile

### ISSUE THREAD

**Issue by heyitsjeoff** [egandunning/learn-crypto#22]
Hash on Hash

**Comment by heyitsjeoff** [comment]
Why is Egan the majority of the commits @Quintonamore @passanpm

**Comment by passanpm** [comment]
@heyitsjeoff Quinton and I are working to install Linux Mint on our machines because the program does not work on other operating systems at this moment. Only Egan's machine can use the program right now.

**Comment by Quintonamore** [comment]
👀

**Comment by egandunning** [comment]
👀
