### ISSUE TITLE
Make class to convert strings to byte array. - 2

### ISSUE THREAD

**Issue by egandunning** [egandunning/learn-crypto#24]
Some cryptopp functions output byte arrays and require byte arrays as input.

**Comment by daw42** [comment]
`QString` already has support for this.  Have you looked at these?

[`QString::toUtf8()`](http://doc.qt.io/qt-5/qstring.html#toUtf8)
[`QString::QString(QByteArray&)`](http://doc.qt.io/qt-5/qstring.html#QString-8)
[`QString::fromUtf8(QByteArray &)`](http://doc.qt.io/qt-5/qstring.html#fromUtf8)

**Comment by egandunning** [comment]
I didn't know about those. I tried that out and found that it was easier to use `unsigned char*` instead, since `byte` and `unsigned char` are interchangeable.
